### ISSUE TITLE
Compiling a project with multiple files

### ISSUE THREAD

**Issue by andre-dietrich** [ponty/pyavrutils#1]
Hi there, 

first of all, great tool ;)
secondly, I would like to compile an arduino project that contains multiple source and header files next to a basic sketch.ino... but somehow, those additional files are not found. Here is a minimal example:

``` python
from pyavrutils import Arduino

arduino_code = open('../sketch/sketch.ino').read()

arduino = Arduino()

arduino.mcu = 'atmega2560'
arduino.build(arduino_code)
...
```

and the output is:

``` bash
Traceback (most recent call last):
  File "avr.py", line 34, in <module>
    arduino.build(arduino_code)
  File "/usr/local/lib/python2.7/dist-packages/pyavrutils/arduino.py", line 184, in build
    self.build_arscons(sources=sources)
  File "/usr/local/lib/python2.7/dist-packages/pyavrutils/arduino.py", line 219, in build_arscons
    raise ArduinoCompileError(cmd, sources, self.error_text)
pyavrutils.arduino.ArduinoCompileError: compile error! 
 cmd =['scons', 'ARDUINO_HARDWARE_PACKAGE=arduino', 'MCU=atmega2560', 'F_CPU=16000000', 'EXTRA_LIB=~/Arduino/libraries/SSOS']
 sources= #include <opcode.h>

void setup() {
  ...
}
...
void loop() {
...
}
 error_text=
   build/pyavrutils_Ufd6qX.ino:1:20: fatal error: opcode.h: No such file or directory
```

Although they are found, if I compile the project with the arduino-GUI itself. I already tried to copy, the additional files to `~/Arduino/library/xxx` or `~/sketchbook/libraries/xxx`. Additionally I tried to set `arduino.arduino_home` or `arduino.extra_lib`, but nothing worked. 

Do you have any suggestions, or could provide me a simple example?

Regards

**Comment by ponty** [comment]
Try this:

``` python
arduino.build('../sketch/sketch.ino')
```

**Comment by andre-dietrich** [comment]
thx, it solved my problem ...
